controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    pilbot_controller:
      type: diff_drive_controller/DiffDriveController

pilbot_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    use_stamped_vel: true
    left_wheel_names: ["wheel_left_joint"]
    right_wheel_names: ["wheel_right_joint"]

    publish_rate: 100.0
    pose_covariance_diagonal: [0.001, 0.001, 1e-3, 1e-3, 1e-3, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 1e-3, 1e-3, 1e-3, 0.01]

    wheel_separation: 0.19 #  + 0.02 error
    wheel_radius: 0.038    #  + 0.005 error

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0  

    cmd_vel_timeout: 0.5
    odom_frame_id: odom
    base_frame_id: base_footprint

    publish_limited_velocity: true
    publish_wheel_data: true
    enable_odom_tf: true
    open_loop: false
    position_feedback: true
    

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.5
        min_velocity: -0.75
        has_acceleration_limits: true
        max_acceleration: 0.8
        min_acceleration: -0.4
        has_jerk_limits: true
        max_jerk: 5.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 2.0
        min_velocity: -2.0
        has_acceleration_limits: true
        max_acceleration: 1.0
        min_acceleration: -1.0
        has_jerk_limits: true
        max_jerk: 2.5