controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    pilbot_controller:
      type: diff_drive_controller/DiffDriveController

    simple_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

pilbot_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    use_stamped_vel: true
    left_wheel_names: ["wheel_left_joint"]
    right_wheel_names: ["wheel_right_joint"]

    publish_rate: 100.0
    pose_covariance_diagonal: [0.001, 0.001, 1e-3, 1e-3, 1e-3, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 1e-3, 1e-3, 1e-3, 0.01]

    wheel_separation: 0.19 #  + 0.02 error
    wheel_radius: 0.038    #  + 0.005 error

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0  

    cmd_vel_timeout: 0.5
    odom_frame_id: odom
    base_frame_id: base_footprint

    publish_limited_velocity: true
    publish_wheel_data: true
    enable_odom_tf: true



simple_velocity_controller:
  ros__parameters:
    joints:
      - wheel_left_joint
      - wheel_right_joint